# This is a TOML document. Boom.

# store golang pprof
Pprof = true
PprofListen  = "localhost:6060"

# store stat listen
StatListen   = "localhost:6061"

# api listen, get/upload/delete
ApiListen    = "localhost:6062"

# admin listen, add/del volume
AdminListen  = "localhost:6063"

# needle(pic) max size
NeedleMaxSize  = 10485760

# max batch upload 
BatchMaxNum    = 9

[Store]
# volume meta index
VolumeIndex      = "/tmp/volume.idx"

# free volume meta index
FreeVolumeIndex  = "/tmp/free_volume.idx"

[Volume]
# sync delete operation after N delete
SyncDelete  = 1024

# sync delete delay duration
SyncDeleteDelay  = "10s"

[Block]
# sync write operation after N write
SyncWrite      = 1

# use new kernel syscall syncfilerange
Syncfilerange  = true

[Index]
# index bufio size
BufferSize = 4096

# merge delay duration
MergeDelay  =  "10s"

# merge write after N write
MergeWrite  = 1024

# ring buffer cache
RingBuffer  = 10240

# sync write operation after N write
SyncWrite   = 1024

# use new kernel syscall syncfilerange
Syncfilerange = true

[Limit]
# rate r and permits bursts of at most settings
# 
# limit read iops speed
[Limit.Read]
Rate = 150.0
Brust = 50
# limit write iops speed
[Limit.Write]
Rate = 150.0
Brust = 50
# limit delete iops speed
[Limit.Delete]
Rate = 150.0
Brust = 50

[Zookeeper]
# zookeeper root path.
Root  =  "/rack"

# store machine in which rack.
Rack  =  "bfs-test"

# serverid for store server, must unique in cluster
ServerId  = "47E273ED-CD3A-4D6A-94CE-554BA9B195EB"

# zookeeper cluster addrs
Addrs = [
    "localhost:2181"
]

# zookeeper heartbeat timeout.
Timeout = "1s"
